//go:build integration

package docoutput_test

import (
	"context"
	"database/sql"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/Gujiaweiguo/mi/backend/internal/billing"
	"github.com/Gujiaweiguo/mi/backend/internal/config"
	"github.com/Gujiaweiguo/mi/backend/internal/docoutput"
	"github.com/Gujiaweiguo/mi/backend/internal/invoice"
	"github.com/Gujiaweiguo/mi/backend/internal/lease"
	platformdb "github.com/Gujiaweiguo/mi/backend/internal/platform/database"
	"github.com/Gujiaweiguo/mi/backend/internal/workflow"
	_ "github.com/go-sql-driver/mysql"
)

var docOutputWorkflowNow = func() time.Time { return time.Date(2026, 4, 1, 9, 0, 0, 0, time.UTC) }

func TestDocOutputServiceRendersInvoiceBatchGoldenHTMLAndPDF(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	db := platformdb.NewTestDB(t, ctx, os.DirFS("../platform/database"))
	service, invoiceID, _, generatedPath := newDocOutputHarness(t, ctx, db)

	if _, err := service.UpsertTemplate(ctx, docoutput.UpsertTemplateInput{Code: "invoice-batch-default", Name: "Invoice Batch Default", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceBatch, Title: "Lease Invoice Batch Print", Subtitle: "Default invoice batch layout", HeaderLines: []string{"Sunshine Commercial MI", "Finance Department"}, FooterLines: []string{"Approved invoice output", "Generated by MI"}, ActorUserID: 101}); err != nil {
		t.Fatalf("upsert invoice batch template: %v", err)
	}

	htmlArtifact, err := service.RenderHTML(ctx, docoutput.RenderInput{TemplateCode: "invoice-batch-default", DocumentIDs: []int64{invoiceID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("render invoice batch html: %v", err)
	}
	expectedHTML, err := os.ReadFile(filepath.Join("testdata", "invoice_batch_expected.html"))
	if err != nil {
		t.Fatalf("read expected invoice batch html: %v", err)
	}
	if strings.TrimSpace(string(htmlArtifact.Body)) != strings.TrimSpace(string(expectedHTML)) {
		t.Fatalf("invoice batch html mismatch\nexpected:\n%s\nactual:\n%s", string(expectedHTML), string(htmlArtifact.Body))
	}

	pdfArtifact, err := service.RenderPDF(ctx, docoutput.RenderInput{TemplateCode: "invoice-batch-default", DocumentIDs: []int64{invoiceID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("render invoice batch pdf: %v", err)
	}
	if pdfArtifact.ContentType != "application/pdf" || !strings.HasPrefix(string(pdfArtifact.Body), "%PDF") {
		t.Fatalf("expected pdf artifact, got contentType=%s size=%d", pdfArtifact.ContentType, len(pdfArtifact.Body))
	}
	if _, err := os.Stat(generatedPath); err != nil {
		t.Fatalf("expected generated documents path to exist: %v", err)
	}
}

func TestDocOutputServiceRendersBillStateGoldenHTML(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	db := platformdb.NewTestDB(t, ctx, os.DirFS("../platform/database"))
	service, _, billID, _ := newDocOutputHarness(t, ctx, db)

	if _, err := service.UpsertTemplate(ctx, docoutput.UpsertTemplateInput{Code: "bill-state-default", Name: "Bill State Default", DocumentType: "bill", OutputMode: docoutput.OutputModeBillState, Title: "Bill Printable State", Subtitle: "Approved bill state", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"Bill is printable after approval"}, ActorUserID: 101}); err != nil {
		t.Fatalf("upsert bill state template: %v", err)
	}

	htmlArtifact, err := service.RenderHTML(ctx, docoutput.RenderInput{TemplateCode: "bill-state-default", DocumentIDs: []int64{billID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("render bill state html: %v", err)
	}
	expectedHTML, err := os.ReadFile(filepath.Join("testdata", "bill_state_expected.html"))
	if err != nil {
		t.Fatalf("read expected bill state html: %v", err)
	}
	if strings.TrimSpace(string(htmlArtifact.Body)) != strings.TrimSpace(string(expectedHTML)) {
		t.Fatalf("bill state html mismatch\nexpected:\n%s\nactual:\n%s", string(expectedHTML), string(htmlArtifact.Body))
	}
}

func TestDocOutputServiceRendersInvoiceDetailGoldenHTML(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	db := platformdb.NewTestDB(t, ctx, os.DirFS("../platform/database"))
	service, invoiceID, _, _ := newDocOutputHarness(t, ctx, db)

	if _, err := service.UpsertTemplate(ctx, docoutput.UpsertTemplateInput{Code: "invoice-detail-default", Name: "Invoice Detail Default", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceDetail, Title: "Invoice Detail Print", Subtitle: "Printable invoice detail", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"Invoice detail output"}, ActorUserID: 101}); err != nil {
		t.Fatalf("upsert invoice detail template: %v", err)
	}

	htmlArtifact, err := service.RenderHTML(ctx, docoutput.RenderInput{TemplateCode: "invoice-detail-default", DocumentIDs: []int64{invoiceID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("render invoice detail html: %v", err)
	}
	expectedHTML, err := os.ReadFile(filepath.Join("testdata", "invoice_detail_expected.html"))
	if err != nil {
		t.Fatalf("read expected invoice detail html: %v", err)
	}
	if strings.TrimSpace(string(htmlArtifact.Body)) != strings.TrimSpace(string(expectedHTML)) {
		t.Fatalf("invoice detail html mismatch\nexpected:\n%s\nactual:\n%s", string(expectedHTML), string(htmlArtifact.Body))
	}
}

func TestDocOutputServiceSupportsConfiguredPrintVariants(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	db := platformdb.NewTestDB(t, ctx, os.DirFS("../platform/database"))
	service, invoiceID, _, _ := newDocOutputHarness(t, ctx, db)

	variantCases := []docoutput.UpsertTemplateInput{
		{Code: "invoice-batch-area", Name: "Invoice Batch Area", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceBatch, Title: "Lease Invoice Batch Print (Area)", Subtitle: "Area-oriented invoice batch layout", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"Area invoice batch output"}, ActorUserID: 101},
		{Code: "invoice-batch-ad-board", Name: "Invoice Batch Ad Board", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceBatch, Title: "Lease Invoice Batch Print (Ad Board)", Subtitle: "Ad-board invoice batch layout", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"Ad-board invoice batch output"}, ActorUserID: 101},
		{Code: "invoice-batch-jv", Name: "Invoice Batch JV", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceBatch, Title: "JV / Unit Invoice Batch Print", Subtitle: "JV invoice batch layout", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"JV invoice batch output"}, ActorUserID: 101},
		{Code: "invoice-reprint-default", Name: "Invoice Reprint Default", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceDetail, Title: "Lease Invoice Reprint", Subtitle: "Reprint invoice detail layout", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"Invoice reprint output"}, ActorUserID: 101},
		{Code: "invoice-reprint-jv", Name: "Invoice Reprint JV", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceDetail, Title: "JV / Unit Invoice Reprint", Subtitle: "JV invoice reprint layout", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"JV invoice reprint output"}, ActorUserID: 101},
		{Code: "interest-invoice-default", Name: "Interest Invoice Default", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceDetail, Title: "Interest Invoice Print", Subtitle: "Printable interest invoice detail", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"Interest invoice output"}, ActorUserID: 101},
	}

	for _, variant := range variantCases {
		if _, err := service.UpsertTemplate(ctx, variant); err != nil {
			t.Fatalf("upsert variant template %s: %v", variant.Code, err)
		}

		htmlArtifact, err := service.RenderHTML(ctx, docoutput.RenderInput{TemplateCode: variant.Code, DocumentIDs: []int64{invoiceID}, ActorUserID: 101})
		if err != nil {
			t.Fatalf("render variant template %s: %v", variant.Code, err)
		}
		if !strings.Contains(string(htmlArtifact.Body), variant.Title) || !strings.Contains(string(htmlArtifact.Body), "INV-") {
			t.Fatalf("expected rendered html for %s to contain title and invoice number, got %s", variant.Code, string(htmlArtifact.Body))
		}
	}
}

func newDocOutputHarness(t *testing.T, ctx context.Context, db *sql.DB) (*docoutput.Service, int64, int64, string) {
	t.Helper()
	workflowService := workflow.NewService(db, workflow.NewRepositoryWithNowFunc(db, docOutputWorkflowNow))
	leaseService := lease.NewService(db, lease.NewRepository(db), workflowService)
	billingRepo := billing.NewRepository(db)
	billingService := billing.NewService(db, billingRepo)
	invoiceService := invoice.NewService(db, invoice.NewRepository(db), billingRepo, workflowService)
	generatedPath := t.TempDir()
	service := docoutput.NewService(docoutput.NewRepository(db), invoiceService, config.StorageConfig{GeneratedDocumentsPath: generatedPath})
	activateLeaseForPrint(t, ctx, leaseService, workflowService, "CON-PRINT-101", "submit-print-lease-1")
	charges, err := billingService.GenerateCharges(ctx, billing.GenerateInput{PeriodStart: time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC), PeriodEnd: time.Date(2026, 4, 30, 0, 0, 0, 0, time.UTC), ActorUserID: 101})
	if err != nil {
		t.Fatalf("generate invoice charges: %v", err)
	}
	invoiceDoc, err := invoiceService.CreateFromCharges(ctx, invoice.CreateInput{DocumentType: invoice.DocumentTypeInvoice, BillingChargeLineIDs: []int64{charges.Lines[0].ID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("create invoice document: %v", err)
	}

	activateLeaseForPrint(t, ctx, leaseService, workflowService, "CON-PRINT-102", "submit-print-lease-2")
	charges, err = billingService.GenerateCharges(ctx, billing.GenerateInput{PeriodStart: time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC), PeriodEnd: time.Date(2026, 4, 30, 0, 0, 0, 0, time.UTC), ActorUserID: 101})
	if err != nil {
		t.Fatalf("generate bill charges: %v", err)
	}
	billDoc, err := invoiceService.CreateFromCharges(ctx, invoice.CreateInput{DocumentType: invoice.DocumentTypeBill, BillingChargeLineIDs: []int64{charges.Lines[0].ID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("create bill document: %v", err)
	}
	approvedInvoiceID := approveDocument(t, ctx, invoiceService, workflowService, invoiceDoc.ID, "invoice", 101)
	approvedBillID := approveDocument(t, ctx, invoiceService, workflowService, billDoc.ID, "bill", 101)
	return service, approvedInvoiceID, approvedBillID, generatedPath
}

func activateLeaseForPrint(t *testing.T, ctx context.Context, leaseService *lease.Service, workflowService *workflow.Service, leaseNo, submitKey string) {
	t.Helper()
	start := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	end := time.Date(2027, 3, 31, 0, 0, 0, 0, time.UTC)
	buildingID := int64(101)
	customerID := int64(101)
	brandID := int64(101)
	tradeID := int64(102)
	managementTypeID := int64(101)
	draft, err := leaseService.CreateDraft(ctx, lease.CreateDraftInput{LeaseNo: leaseNo, DepartmentID: 101, StoreID: 101, BuildingID: &buildingID, CustomerID: &customerID, BrandID: &brandID, TradeID: &tradeID, ManagementTypeID: &managementTypeID, TenantName: "ACME Retail", StartDate: start, EndDate: end, Units: []lease.UnitInput{{UnitID: 101, RentArea: 118}}, Terms: []lease.TermInput{{TermType: lease.TermTypeRent, BillingCycle: lease.BillingCycleMonthly, CurrencyTypeID: 101, Amount: 12000, EffectiveFrom: start, EffectiveTo: end}}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("create lease draft: %v", err)
	}
	submittedLease, err := leaseService.SubmitForApproval(ctx, lease.SubmitInput{LeaseID: draft.ID, ActorUserID: 101, DepartmentID: 101, IdempotencyKey: submitKey, Comment: "submit lease"})
	if err != nil {
		t.Fatalf("submit lease: %v", err)
	}
	instance, err := workflowService.Approve(ctx, workflow.TransitionInput{InstanceID: *submittedLease.WorkflowInstanceID, ActorUserID: 101, DepartmentID: 101, IdempotencyKey: submitKey + "-step1", Comment: "manager approved"})
	if err != nil {
		t.Fatalf("approve lease step 1: %v", err)
	}
	if err := leaseService.SyncWorkflowState(ctx, instance, 101); err != nil {
		t.Fatalf("sync lease step 1: %v", err)
	}
	instance, err = workflowService.Approve(ctx, workflow.TransitionInput{InstanceID: *submittedLease.WorkflowInstanceID, ActorUserID: 101, DepartmentID: 101, IdempotencyKey: submitKey + "-step2", Comment: "finance approved"})
	if err != nil {
		t.Fatalf("approve lease step 2: %v", err)
	}
	if err := leaseService.SyncWorkflowState(ctx, instance, 101); err != nil {
		t.Fatalf("sync lease step 2: %v", err)
	}
}

func approveDocument(t *testing.T, ctx context.Context, invoiceService *invoice.Service, workflowService *workflow.Service, documentID int64, kind string, actorUserID int64) int64 {
	t.Helper()
	submitted, err := invoiceService.SubmitForApproval(ctx, invoice.SubmitInput{DocumentID: documentID, ActorUserID: actorUserID, DepartmentID: 101, IdempotencyKey: "submit-" + kind + "-print", Comment: "submit document"})
	if err != nil {
		t.Fatalf("submit %s document: %v", kind, err)
	}
	instance, err := workflowService.Approve(ctx, workflow.TransitionInput{InstanceID: *submitted.WorkflowInstanceID, ActorUserID: actorUserID, DepartmentID: 101, IdempotencyKey: "approve-" + kind + "-print", Comment: "finance approved"})
	if err != nil {
		t.Fatalf("approve %s document: %v", kind, err)
	}
	if err := invoiceService.SyncWorkflowState(ctx, instance, actorUserID); err != nil {
		t.Fatalf("sync %s document approval: %v", kind, err)
	}
	return documentID
}
