//go:build integration

package docoutput_test

import (
	"context"
	"database/sql"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/Gujiaweiguo/mi/backend/internal/billing"
	"github.com/Gujiaweiguo/mi/backend/internal/config"
	"github.com/Gujiaweiguo/mi/backend/internal/docoutput"
	"github.com/Gujiaweiguo/mi/backend/internal/invoice"
	"github.com/Gujiaweiguo/mi/backend/internal/lease"
	platformdb "github.com/Gujiaweiguo/mi/backend/internal/platform/database"
	bootstrap "github.com/Gujiaweiguo/mi/backend/internal/platform/database/bootstrap"
	"github.com/Gujiaweiguo/mi/backend/internal/workflow"
	_ "github.com/go-sql-driver/mysql"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

var docOutputWorkflowNow = func() time.Time { return time.Date(2026, 4, 1, 9, 0, 0, 0, time.UTC) }

func TestDocOutputServiceRendersInvoiceBatchGoldenHTMLAndPDF(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	db := newDocOutputTestDB(t, ctx)
	service, invoiceID, _, generatedPath := newDocOutputHarness(t, ctx, db)

	if _, err := service.UpsertTemplate(ctx, docoutput.UpsertTemplateInput{Code: "invoice-batch-default", Name: "Invoice Batch Default", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceBatch, Title: "Lease Invoice Batch Print", Subtitle: "Default invoice batch layout", HeaderLines: []string{"Sunshine Commercial MI", "Finance Department"}, FooterLines: []string{"Approved invoice output", "Generated by MI"}, ActorUserID: 101}); err != nil {
		t.Fatalf("upsert invoice batch template: %v", err)
	}

	htmlArtifact, err := service.RenderHTML(ctx, docoutput.RenderInput{TemplateCode: "invoice-batch-default", DocumentIDs: []int64{invoiceID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("render invoice batch html: %v", err)
	}
	expectedHTML, err := os.ReadFile(filepath.Join("testdata", "invoice_batch_expected.html"))
	if err != nil {
		t.Fatalf("read expected invoice batch html: %v", err)
	}
	if strings.TrimSpace(string(htmlArtifact.Body)) != strings.TrimSpace(string(expectedHTML)) {
		t.Fatalf("invoice batch html mismatch\nexpected:\n%s\nactual:\n%s", string(expectedHTML), string(htmlArtifact.Body))
	}

	pdfArtifact, err := service.RenderPDF(ctx, docoutput.RenderInput{TemplateCode: "invoice-batch-default", DocumentIDs: []int64{invoiceID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("render invoice batch pdf: %v", err)
	}
	if pdfArtifact.ContentType != "application/pdf" || !strings.HasPrefix(string(pdfArtifact.Body), "%PDF") {
		t.Fatalf("expected pdf artifact, got contentType=%s size=%d", pdfArtifact.ContentType, len(pdfArtifact.Body))
	}
	if _, err := os.Stat(generatedPath); err != nil {
		t.Fatalf("expected generated documents path to exist: %v", err)
	}
}

func TestDocOutputServiceRendersBillStateGoldenHTML(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	db := newDocOutputTestDB(t, ctx)
	service, _, billID, _ := newDocOutputHarness(t, ctx, db)

	if _, err := service.UpsertTemplate(ctx, docoutput.UpsertTemplateInput{Code: "bill-state-default", Name: "Bill State Default", DocumentType: "bill", OutputMode: docoutput.OutputModeBillState, Title: "Bill Printable State", Subtitle: "Approved bill state", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"Bill is printable after approval"}, ActorUserID: 101}); err != nil {
		t.Fatalf("upsert bill state template: %v", err)
	}

	htmlArtifact, err := service.RenderHTML(ctx, docoutput.RenderInput{TemplateCode: "bill-state-default", DocumentIDs: []int64{billID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("render bill state html: %v", err)
	}
	expectedHTML, err := os.ReadFile(filepath.Join("testdata", "bill_state_expected.html"))
	if err != nil {
		t.Fatalf("read expected bill state html: %v", err)
	}
	if strings.TrimSpace(string(htmlArtifact.Body)) != strings.TrimSpace(string(expectedHTML)) {
		t.Fatalf("bill state html mismatch\nexpected:\n%s\nactual:\n%s", string(expectedHTML), string(htmlArtifact.Body))
	}
}

func TestDocOutputServiceRendersInvoiceDetailGoldenHTML(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	db := newDocOutputTestDB(t, ctx)
	service, invoiceID, _, _ := newDocOutputHarness(t, ctx, db)

	if _, err := service.UpsertTemplate(ctx, docoutput.UpsertTemplateInput{Code: "invoice-detail-default", Name: "Invoice Detail Default", DocumentType: "invoice", OutputMode: docoutput.OutputModeInvoiceDetail, Title: "Invoice Detail Print", Subtitle: "Printable invoice detail", HeaderLines: []string{"Sunshine Commercial MI"}, FooterLines: []string{"Invoice detail output"}, ActorUserID: 101}); err != nil {
		t.Fatalf("upsert invoice detail template: %v", err)
	}

	htmlArtifact, err := service.RenderHTML(ctx, docoutput.RenderInput{TemplateCode: "invoice-detail-default", DocumentIDs: []int64{invoiceID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("render invoice detail html: %v", err)
	}
	expectedHTML, err := os.ReadFile(filepath.Join("testdata", "invoice_detail_expected.html"))
	if err != nil {
		t.Fatalf("read expected invoice detail html: %v", err)
	}
	if strings.TrimSpace(string(htmlArtifact.Body)) != strings.TrimSpace(string(expectedHTML)) {
		t.Fatalf("invoice detail html mismatch\nexpected:\n%s\nactual:\n%s", string(expectedHTML), string(htmlArtifact.Body))
	}
}

func newDocOutputHarness(t *testing.T, ctx context.Context, db *sql.DB) (*docoutput.Service, int64, int64, string) {
	t.Helper()
	workflowService := workflow.NewService(db, workflow.NewRepositoryWithNowFunc(db, docOutputWorkflowNow))
	leaseService := lease.NewService(db, lease.NewRepository(db), workflowService)
	billingRepo := billing.NewRepository(db)
	billingService := billing.NewService(db, billingRepo)
	invoiceService := invoice.NewService(db, invoice.NewRepository(db), billingRepo, workflowService)
	generatedPath := t.TempDir()
	service := docoutput.NewService(docoutput.NewRepository(db), invoiceService, config.StorageConfig{GeneratedDocumentsPath: generatedPath})
	activateLeaseForPrint(t, ctx, leaseService, workflowService, "CON-PRINT-101", "submit-print-lease-1")
	charges, err := billingService.GenerateCharges(ctx, billing.GenerateInput{PeriodStart: time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC), PeriodEnd: time.Date(2026, 4, 30, 0, 0, 0, 0, time.UTC), ActorUserID: 101})
	if err != nil {
		t.Fatalf("generate invoice charges: %v", err)
	}
	invoiceDoc, err := invoiceService.CreateFromCharges(ctx, invoice.CreateInput{DocumentType: invoice.DocumentTypeInvoice, BillingChargeLineIDs: []int64{charges.Lines[0].ID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("create invoice document: %v", err)
	}

	activateLeaseForPrint(t, ctx, leaseService, workflowService, "CON-PRINT-102", "submit-print-lease-2")
	charges, err = billingService.GenerateCharges(ctx, billing.GenerateInput{PeriodStart: time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC), PeriodEnd: time.Date(2026, 4, 30, 0, 0, 0, 0, time.UTC), ActorUserID: 101})
	if err != nil {
		t.Fatalf("generate bill charges: %v", err)
	}
	billDoc, err := invoiceService.CreateFromCharges(ctx, invoice.CreateInput{DocumentType: invoice.DocumentTypeBill, BillingChargeLineIDs: []int64{charges.Lines[0].ID}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("create bill document: %v", err)
	}
	approvedInvoiceID := approveDocument(t, ctx, invoiceService, workflowService, invoiceDoc.ID, "invoice", 101)
	approvedBillID := approveDocument(t, ctx, invoiceService, workflowService, billDoc.ID, "bill", 101)
	return service, approvedInvoiceID, approvedBillID, generatedPath
}

func activateLeaseForPrint(t *testing.T, ctx context.Context, leaseService *lease.Service, workflowService *workflow.Service, leaseNo, submitKey string) {
	t.Helper()
	start := time.Date(2026, 4, 1, 0, 0, 0, 0, time.UTC)
	end := time.Date(2027, 3, 31, 0, 0, 0, 0, time.UTC)
	buildingID := int64(101)
	customerID := int64(101)
	brandID := int64(101)
	tradeID := int64(102)
	managementTypeID := int64(101)
	draft, err := leaseService.CreateDraft(ctx, lease.CreateDraftInput{LeaseNo: leaseNo, DepartmentID: 101, StoreID: 101, BuildingID: &buildingID, CustomerID: &customerID, BrandID: &brandID, TradeID: &tradeID, ManagementTypeID: &managementTypeID, TenantName: "ACME Retail", StartDate: start, EndDate: end, Units: []lease.UnitInput{{UnitID: 101, RentArea: 118}}, Terms: []lease.TermInput{{TermType: lease.TermTypeRent, BillingCycle: lease.BillingCycleMonthly, CurrencyTypeID: 101, Amount: 12000, EffectiveFrom: start, EffectiveTo: end}}, ActorUserID: 101})
	if err != nil {
		t.Fatalf("create lease draft: %v", err)
	}
	submittedLease, err := leaseService.SubmitForApproval(ctx, lease.SubmitInput{LeaseID: draft.ID, ActorUserID: 101, DepartmentID: 101, IdempotencyKey: submitKey, Comment: "submit lease"})
	if err != nil {
		t.Fatalf("submit lease: %v", err)
	}
	instance, err := workflowService.Approve(ctx, workflow.TransitionInput{InstanceID: *submittedLease.WorkflowInstanceID, ActorUserID: 101, DepartmentID: 101, IdempotencyKey: submitKey + "-step1", Comment: "manager approved"})
	if err != nil {
		t.Fatalf("approve lease step 1: %v", err)
	}
	if err := leaseService.SyncWorkflowState(ctx, instance, 101); err != nil {
		t.Fatalf("sync lease step 1: %v", err)
	}
	instance, err = workflowService.Approve(ctx, workflow.TransitionInput{InstanceID: *submittedLease.WorkflowInstanceID, ActorUserID: 101, DepartmentID: 101, IdempotencyKey: submitKey + "-step2", Comment: "finance approved"})
	if err != nil {
		t.Fatalf("approve lease step 2: %v", err)
	}
	if err := leaseService.SyncWorkflowState(ctx, instance, 101); err != nil {
		t.Fatalf("sync lease step 2: %v", err)
	}
}

func approveDocument(t *testing.T, ctx context.Context, invoiceService *invoice.Service, workflowService *workflow.Service, documentID int64, kind string, actorUserID int64) int64 {
	t.Helper()
	submitted, err := invoiceService.SubmitForApproval(ctx, invoice.SubmitInput{DocumentID: documentID, ActorUserID: actorUserID, DepartmentID: 101, IdempotencyKey: "submit-" + kind + "-print", Comment: "submit document"})
	if err != nil {
		t.Fatalf("submit %s document: %v", kind, err)
	}
	instance, err := workflowService.Approve(ctx, workflow.TransitionInput{InstanceID: *submitted.WorkflowInstanceID, ActorUserID: actorUserID, DepartmentID: 101, IdempotencyKey: "approve-" + kind + "-print", Comment: "finance approved"})
	if err != nil {
		t.Fatalf("approve %s document: %v", kind, err)
	}
	if err := invoiceService.SyncWorkflowState(ctx, instance, actorUserID); err != nil {
		t.Fatalf("sync %s document approval: %v", kind, err)
	}
	return documentID
}

func newDocOutputTestDB(t *testing.T, ctx context.Context) *sql.DB {
	t.Helper()
	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{ContainerRequest: testcontainers.ContainerRequest{Image: "mysql:8.0", ExposedPorts: []string{"3306/tcp"}, Env: map[string]string{"MYSQL_DATABASE": "mi_integration", "MYSQL_USER": "mi_user", "MYSQL_PASSWORD": "mi_password", "MYSQL_ROOT_PASSWORD": "mi_root_password"}, WaitingFor: wait.ForListeningPort("3306/tcp").WithStartupTimeout(3 * time.Minute)}, Started: true})
	if err != nil {
		t.Fatalf("start mysql container: %v", err)
	}
	t.Cleanup(func() { _ = container.Terminate(context.Background()) })
	host, err := container.Host(ctx)
	if err != nil {
		t.Fatalf("resolve mysql host: %v", err)
	}
	port, err := container.MappedPort(ctx, "3306/tcp")
	if err != nil {
		t.Fatalf("resolve mysql port: %v", err)
	}
	db, err := sql.Open("mysql", platformdb.Config{Host: host, Port: port.Int(), Name: "mi_integration", User: "mi_user", Password: "mi_password"}.DSN())
	if err != nil {
		t.Fatalf("open mysql connection: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })
	if err := waitForDatabase(ctx, db); err != nil {
		t.Fatalf("wait for mysql: %v", err)
	}
	migrator := platformdb.NewMigrator(db, os.DirFS("../platform/database"), "migrations")
	if err := migrator.ApplyUpMigrations(); err != nil {
		t.Fatalf("apply migrations: %v", err)
	}
	bootstrapRunner := platformdb.NewBootstrapRunner(db, bootstrap.All()...)
	if err := bootstrapRunner.Run(ctx); err != nil {
		t.Fatalf("run bootstrap seeds: %v", err)
	}
	return db
}

func waitForDatabase(ctx context.Context, db *sql.DB) error {
	deadline := time.Now().Add(30 * time.Second)
	var lastErr error
	for time.Now().Before(deadline) {
		pingCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
		lastErr = db.PingContext(pingCtx)
		cancel()
		if lastErr == nil {
			return nil
		}
		time.Sleep(500 * time.Millisecond)
	}
	return lastErr
}
