CREATE TABLE deposit_applications (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  source_billing_document_id BIGINT NOT NULL,
  source_billing_document_line_id BIGINT NOT NULL,
  source_ar_open_item_id BIGINT NOT NULL,
  target_billing_document_id BIGINT NOT NULL,
  target_billing_document_line_id BIGINT NOT NULL,
  target_ar_open_item_id BIGINT NOT NULL,
  lease_contract_id BIGINT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  note VARCHAR(255) NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  applied_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_deposit_applications_idempotency (source_billing_document_id, idempotency_key),
  KEY idx_deposit_applications_source_document (source_billing_document_id),
  KEY idx_deposit_applications_target_document (target_billing_document_id),
  CONSTRAINT fk_deposit_app_source_document FOREIGN KEY (source_billing_document_id) REFERENCES billing_documents(id),
  CONSTRAINT fk_deposit_app_source_line FOREIGN KEY (source_billing_document_line_id) REFERENCES billing_document_lines(id),
  CONSTRAINT fk_deposit_app_source_open_item FOREIGN KEY (source_ar_open_item_id) REFERENCES ar_open_items(id),
  CONSTRAINT fk_deposit_app_target_document FOREIGN KEY (target_billing_document_id) REFERENCES billing_documents(id),
  CONSTRAINT fk_deposit_app_target_line FOREIGN KEY (target_billing_document_line_id) REFERENCES billing_document_lines(id),
  CONSTRAINT fk_deposit_app_target_open_item FOREIGN KEY (target_ar_open_item_id) REFERENCES ar_open_items(id),
  CONSTRAINT fk_deposit_app_applied_by FOREIGN KEY (applied_by) REFERENCES users(id)
);

CREATE TABLE deposit_refunds (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  billing_document_id BIGINT NOT NULL,
  billing_document_line_id BIGINT NOT NULL,
  ar_open_item_id BIGINT NOT NULL,
  lease_contract_id BIGINT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  reason VARCHAR(255) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  refunded_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_deposit_refunds_idempotency (billing_document_id, idempotency_key),
  KEY idx_deposit_refunds_document (billing_document_id),
  CONSTRAINT fk_deposit_refunds_document FOREIGN KEY (billing_document_id) REFERENCES billing_documents(id),
  CONSTRAINT fk_deposit_refunds_line FOREIGN KEY (billing_document_line_id) REFERENCES billing_document_lines(id),
  CONSTRAINT fk_deposit_refunds_open_item FOREIGN KEY (ar_open_item_id) REFERENCES ar_open_items(id),
  CONSTRAINT fk_deposit_refunds_refunded_by FOREIGN KEY (refunded_by) REFERENCES users(id)
);
