CREATE TABLE billing_documents (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  document_type VARCHAR(16) NOT NULL,
  document_no VARCHAR(64) NULL,
  billing_run_id BIGINT NOT NULL,
  lease_contract_id BIGINT NOT NULL,
  tenant_name VARCHAR(128) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL,
  currency_type_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL,
  workflow_instance_id BIGINT NULL,
  adjusted_from_id BIGINT NULL,
  submitted_at TIMESTAMP NULL,
  approved_at TIMESTAMP NULL,
  cancelled_at TIMESTAMP NULL,
  created_by BIGINT NOT NULL,
  updated_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_billing_documents_no (document_no),
  KEY idx_billing_documents_type_status (document_type, status),
  KEY idx_billing_documents_lease_run (lease_contract_id, billing_run_id),
  CONSTRAINT fk_billing_documents_run FOREIGN KEY (billing_run_id) REFERENCES billing_runs(id),
  CONSTRAINT fk_billing_documents_lease FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id),
  CONSTRAINT fk_billing_documents_currency FOREIGN KEY (currency_type_id) REFERENCES currency_types(id),
  CONSTRAINT fk_billing_documents_workflow FOREIGN KEY (workflow_instance_id) REFERENCES workflow_instances(id),
  CONSTRAINT fk_billing_documents_adjusted_from FOREIGN KEY (adjusted_from_id) REFERENCES billing_documents(id),
  CONSTRAINT fk_billing_documents_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_billing_documents_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE billing_document_lines (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  billing_document_id BIGINT NOT NULL,
  billing_charge_line_id BIGINT NOT NULL,
  charge_type VARCHAR(32) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  quantity_days INT NOT NULL,
  unit_amount DECIMAL(12,2) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_billing_document_line_charge (billing_document_id, billing_charge_line_id),
  CONSTRAINT fk_billing_document_lines_document FOREIGN KEY (billing_document_id) REFERENCES billing_documents(id) ON DELETE CASCADE,
  CONSTRAINT fk_billing_document_lines_charge FOREIGN KEY (billing_charge_line_id) REFERENCES billing_charge_lines(id)
);
