-- Revert AUTO_INCREMENT: remove AUTO_INCREMENT from all 13 tables.

ALTER TABLE store_types MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE store_management_types MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE stores MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE area_levels MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE areas MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE unit_types MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE buildings MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE floors MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE locations MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE shop_types MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE trade_definitions MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE currency_types MODIFY COLUMN id BIGINT NOT NULL;
ALTER TABLE units MODIFY COLUMN id BIGINT NOT NULL;
