CREATE TABLE overtime_bills (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  lease_contract_id BIGINT NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  status VARCHAR(32) NOT NULL,
  workflow_instance_id BIGINT NULL,
  note VARCHAR(255) NOT NULL DEFAULT '',
  submitted_at TIMESTAMP NULL,
  approved_at TIMESTAMP NULL,
  rejected_at TIMESTAMP NULL,
  cancelled_at TIMESTAMP NULL,
  stopped_at TIMESTAMP NULL,
  generated_at TIMESTAMP NULL,
  created_by BIGINT NOT NULL,
  updated_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_overtime_bills_contract_period (lease_contract_id, period_start, period_end),
  UNIQUE KEY uq_overtime_bills_workflow_instance (workflow_instance_id),
  KEY idx_overtime_bills_status (status),
  CONSTRAINT fk_overtime_bills_contract FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id),
  CONSTRAINT fk_overtime_bills_workflow_instance FOREIGN KEY (workflow_instance_id) REFERENCES workflow_instances(id),
  CONSTRAINT fk_overtime_bills_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_overtime_bills_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE overtime_bill_formulas (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  overtime_bill_id BIGINT NOT NULL,
  charge_type VARCHAR(32) NOT NULL,
  formula_type VARCHAR(32) NOT NULL,
  rate_type VARCHAR(32) NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NOT NULL,
  currency_type_id BIGINT NOT NULL,
  total_area DECIMAL(12,2) NOT NULL DEFAULT 0,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  base_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  fixed_rental DECIMAL(12,2) NOT NULL DEFAULT 0,
  percentage_option VARCHAR(32) NOT NULL DEFAULT '',
  minimum_option VARCHAR(32) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_overtime_formulas_bill (overtime_bill_id),
  CONSTRAINT fk_overtime_formulas_bill FOREIGN KEY (overtime_bill_id) REFERENCES overtime_bills(id) ON DELETE CASCADE,
  CONSTRAINT fk_overtime_formulas_currency FOREIGN KEY (currency_type_id) REFERENCES currency_types(id)
);

CREATE TABLE overtime_formula_percentage_tiers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  formula_id BIGINT NOT NULL,
  sales_to DECIMAL(12,2) NOT NULL,
  percentage_rate DECIMAL(10,4) NOT NULL,
  sort_order INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_overtime_percentage_tiers_formula (formula_id),
  CONSTRAINT fk_overtime_percentage_tiers_formula FOREIGN KEY (formula_id) REFERENCES overtime_bill_formulas(id) ON DELETE CASCADE
);

CREATE TABLE overtime_formula_minimum_tiers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  formula_id BIGINT NOT NULL,
  sales_to DECIMAL(12,2) NOT NULL,
  minimum_sum DECIMAL(12,2) NOT NULL,
  sort_order INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_overtime_minimum_tiers_formula (formula_id),
  CONSTRAINT fk_overtime_minimum_tiers_formula FOREIGN KEY (formula_id) REFERENCES overtime_bill_formulas(id) ON DELETE CASCADE
);

CREATE TABLE overtime_generated_charges (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  billing_run_id BIGINT NOT NULL,
  overtime_bill_id BIGINT NOT NULL,
  overtime_formula_id BIGINT NOT NULL,
  lease_contract_id BIGINT NOT NULL,
  workflow_instance_id BIGINT NULL,
  charge_type VARCHAR(32) NOT NULL,
  formula_type VARCHAR(32) NOT NULL,
  rate_type VARCHAR(32) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  quantity INT NOT NULL,
  total_area DECIMAL(12,2) NOT NULL DEFAULT 0,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  base_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  fixed_rental DECIMAL(12,2) NOT NULL DEFAULT 0,
  percentage_option VARCHAR(32) NOT NULL DEFAULT '',
  minimum_option VARCHAR(32) NOT NULL DEFAULT '',
  applied_percentage_rate DECIMAL(10,4) NOT NULL DEFAULT 0,
  applied_minimum_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  unit_amount DECIMAL(12,2) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency_type_id BIGINT NOT NULL,
  generated_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_overtime_generated_formula_period (overtime_formula_id, period_start, period_end),
  KEY idx_overtime_generated_bill (overtime_bill_id),
  KEY idx_overtime_generated_run (billing_run_id),
  CONSTRAINT fk_overtime_generated_run FOREIGN KEY (billing_run_id) REFERENCES billing_runs(id),
  CONSTRAINT fk_overtime_generated_bill FOREIGN KEY (overtime_bill_id) REFERENCES overtime_bills(id),
  CONSTRAINT fk_overtime_generated_formula FOREIGN KEY (overtime_formula_id) REFERENCES overtime_bill_formulas(id),
  CONSTRAINT fk_overtime_generated_contract FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id),
  CONSTRAINT fk_overtime_generated_workflow FOREIGN KEY (workflow_instance_id) REFERENCES workflow_instances(id),
  CONSTRAINT fk_overtime_generated_currency FOREIGN KEY (currency_type_id) REFERENCES currency_types(id),
  CONSTRAINT fk_overtime_generated_by FOREIGN KEY (generated_by) REFERENCES users(id)
);
