CREATE TABLE store_types (
  id BIGINT PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE store_management_types (
  id BIGINT PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE stores (
  id BIGINT PRIMARY KEY,
  department_id BIGINT NOT NULL,
  store_type_id BIGINT NOT NULL,
  management_type_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  short_name VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_stores_department FOREIGN KEY (department_id) REFERENCES departments(id),
  CONSTRAINT fk_stores_store_type FOREIGN KEY (store_type_id) REFERENCES store_types(id),
  CONSTRAINT fk_stores_management_type FOREIGN KEY (management_type_id) REFERENCES store_management_types(id)
);

CREATE TABLE area_levels (
  id BIGINT PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE areas (
  id BIGINT PRIMARY KEY,
  store_id BIGINT NOT NULL,
  area_level_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_areas_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_areas_area_level FOREIGN KEY (area_level_id) REFERENCES area_levels(id)
);

CREATE TABLE unit_types (
  id BIGINT PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE buildings (
  id BIGINT PRIMARY KEY,
  store_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_buildings_store FOREIGN KEY (store_id) REFERENCES stores(id)
);

CREATE TABLE floors (
  id BIGINT PRIMARY KEY,
  building_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_floors_building_code (building_id, code),
  CONSTRAINT fk_floors_building FOREIGN KEY (building_id) REFERENCES buildings(id)
);

CREATE TABLE locations (
  id BIGINT PRIMARY KEY,
  store_id BIGINT NOT NULL,
  floor_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_locations_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_locations_floor FOREIGN KEY (floor_id) REFERENCES floors(id)
);

CREATE TABLE shop_types (
  id BIGINT PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE trade_definitions (
  id BIGINT PRIMARY KEY,
  parent_id BIGINT NULL,
  level INT NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_trade_definitions_parent FOREIGN KEY (parent_id) REFERENCES trade_definitions(id)
);

CREATE TABLE currency_types (
  id BIGINT PRIMARY KEY,
  code VARCHAR(16) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  is_local BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE units (
  id BIGINT PRIMARY KEY,
  building_id BIGINT NOT NULL,
  floor_id BIGINT NOT NULL,
  location_id BIGINT NOT NULL,
  area_id BIGINT NOT NULL,
  unit_type_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  floor_area DECIMAL(12,2) NOT NULL,
  use_area DECIMAL(12,2) NOT NULL,
  rent_area DECIMAL(12,2) NOT NULL,
  is_rentable BOOLEAN NOT NULL DEFAULT TRUE,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_units_building FOREIGN KEY (building_id) REFERENCES buildings(id),
  CONSTRAINT fk_units_floor FOREIGN KEY (floor_id) REFERENCES floors(id),
  CONSTRAINT fk_units_location FOREIGN KEY (location_id) REFERENCES locations(id),
  CONSTRAINT fk_units_area FOREIGN KEY (area_id) REFERENCES areas(id),
  CONSTRAINT fk_units_unit_type FOREIGN KEY (unit_type_id) REFERENCES unit_types(id)
);
