CREATE TABLE invoice_discounts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  billing_document_id BIGINT NOT NULL,
  billing_document_line_id BIGINT NOT NULL,
  lease_contract_id BIGINT NOT NULL,
  charge_type VARCHAR(32) NOT NULL,
  requested_amount DECIMAL(12,2) NOT NULL,
  requested_rate DECIMAL(9,6) NOT NULL,
  reason VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  workflow_instance_id BIGINT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  submitted_at TIMESTAMP NULL,
  approved_at TIMESTAMP NULL,
  rejected_at TIMESTAMP NULL,
  created_by BIGINT NOT NULL,
  updated_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_invoice_discounts_document_key (billing_document_id, idempotency_key),
  KEY idx_invoice_discounts_document_status (billing_document_id, status),
  KEY idx_invoice_discounts_line_status (billing_document_line_id, status),
  CONSTRAINT fk_invoice_discounts_document FOREIGN KEY (billing_document_id) REFERENCES billing_documents(id),
  CONSTRAINT fk_invoice_discounts_line FOREIGN KEY (billing_document_line_id) REFERENCES billing_document_lines(id),
  CONSTRAINT fk_invoice_discounts_lease FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id),
  CONSTRAINT fk_invoice_discounts_workflow FOREIGN KEY (workflow_instance_id) REFERENCES workflow_instances(id),
  CONSTRAINT fk_invoice_discounts_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_invoice_discounts_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE ar_discount_entries (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  invoice_discount_id BIGINT NOT NULL,
  billing_document_id BIGINT NOT NULL,
  billing_document_line_id BIGINT NOT NULL,
  ar_open_item_id BIGINT NOT NULL,
  lease_contract_id BIGINT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  recorded_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_ar_discount_entries_discount (invoice_discount_id),
  KEY idx_ar_discount_entries_document (billing_document_id, created_at),
  CONSTRAINT fk_ar_discount_entries_discount FOREIGN KEY (invoice_discount_id) REFERENCES invoice_discounts(id),
  CONSTRAINT fk_ar_discount_entries_document FOREIGN KEY (billing_document_id) REFERENCES billing_documents(id),
  CONSTRAINT fk_ar_discount_entries_line FOREIGN KEY (billing_document_line_id) REFERENCES billing_document_lines(id),
  CONSTRAINT fk_ar_discount_entries_open_item FOREIGN KEY (ar_open_item_id) REFERENCES ar_open_items(id),
  CONSTRAINT fk_ar_discount_entries_lease FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id),
  CONSTRAINT fk_ar_discount_entries_recorded_by FOREIGN KEY (recorded_by) REFERENCES users(id)
);
