DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS functions;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS business_groups;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS department_types;
