CREATE TABLE interest_rate_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  charge_type_filter VARCHAR(32) NULL,
  daily_rate DECIMAL(12,6) NOT NULL,
  grace_days INT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(32) NOT NULL,
  created_by BIGINT NOT NULL,
  updated_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_interest_rate_configs_status_default (status, is_default),
  KEY idx_interest_rate_configs_charge_type (charge_type_filter),
  CONSTRAINT fk_interest_rate_configs_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_interest_rate_configs_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE invoice_interest_entries (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  source_ar_open_item_id BIGINT NOT NULL,
  source_billing_document_id BIGINT NOT NULL,
  source_billing_document_line_id BIGINT NOT NULL,
  generated_billing_document_id BIGINT NOT NULL,
  generated_billing_document_line_id BIGINT NOT NULL,
  charge_type VARCHAR(32) NOT NULL,
  principal_amount DECIMAL(12,2) NOT NULL,
  daily_rate DECIMAL(12,6) NOT NULL,
  grace_days INT NOT NULL,
  covered_start_date DATE NOT NULL,
  covered_end_date DATE NOT NULL,
  interest_days INT NOT NULL,
  interest_amount DECIMAL(12,2) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_invoice_interest_entries_source_period (source_ar_open_item_id, covered_start_date, covered_end_date),
  UNIQUE KEY uq_invoice_interest_entries_source_key (source_ar_open_item_id, idempotency_key),
  KEY idx_invoice_interest_entries_source_document (source_billing_document_id, created_at),
  CONSTRAINT fk_invoice_interest_entries_source_open_item FOREIGN KEY (source_ar_open_item_id) REFERENCES ar_open_items(id),
  CONSTRAINT fk_invoice_interest_entries_source_document FOREIGN KEY (source_billing_document_id) REFERENCES billing_documents(id),
  CONSTRAINT fk_invoice_interest_entries_source_line FOREIGN KEY (source_billing_document_line_id) REFERENCES billing_document_lines(id),
  CONSTRAINT fk_invoice_interest_entries_generated_document FOREIGN KEY (generated_billing_document_id) REFERENCES billing_documents(id),
  CONSTRAINT fk_invoice_interest_entries_generated_line FOREIGN KEY (generated_billing_document_line_id) REFERENCES billing_document_lines(id),
  CONSTRAINT fk_invoice_interest_entries_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);
