global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: mi-backend
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5180']
        labels:
          environment: development
